"""Token-aware session compactor.

Inspired by CLAW Code's compact.rs:
  - Estimate tokens at write time (4 chars/token heuristic)
  - When session exceeds budget, summarize old messages
  - Preserve recent messages verbatim
  - Insert summary as a synthetic system/assistant message

For binary analysis, decompiled functions can be 5000+ chars each, so
compaction is critical for long investigations.
"""

import logging
from typing import List, Optional

from src.runtime.session import Session, Message, MessageRole, ContentBlock

logger = logging.getLogger("agent-g.compactor")


# Default budget — leave headroom for system prompt + new response
DEFAULT_MAX_TOKENS = 12_000  # ~48KB of context
DEFAULT_PRESERVE_RECENT = 6   # Always keep N most-recent messages verbatim


def estimate_message_tokens(message: Message) -> int:
    """Fast token estimate per message (4 chars/token heuristic)."""
    total = 0
    for block in message.blocks:
        if block.text:
            total += len(block.text) // 4 + 1
        if block.tool_output:
            total += len(block.tool_output) // 4 + 1
        if block.tool_name:
            total += len(block.tool_name) // 4 + 1
        if block.tool_input:
            total += len(str(block.tool_input)) // 4 + 1
    return total + 4  # Overhead per message


def estimate_session_tokens(session: Session) -> int:
    """Total estimated tokens across all conversation messages."""
    return sum(
        estimate_message_tokens(m)
        for m in session.messages
        if m.role != MessageRole.SYSTEM
    )


def should_compact(
    session: Session,
    max_tokens: int = DEFAULT_MAX_TOKENS,
    preserve_recent: int = DEFAULT_PRESERVE_RECENT,
) -> bool:
    """Return True if the session should be compacted now."""
    convo = session.conversation_messages()
    if len(convo) <= preserve_recent + 2:
        return False  # Not enough to compact
    return estimate_session_tokens(session) > max_tokens


def compact_session(
    session: Session,
    api_client=None,
    max_tokens: int = DEFAULT_MAX_TOKENS,
    preserve_recent: int = DEFAULT_PRESERVE_RECENT,
) -> Session:
    """Return a new session with old messages summarized.

    The summary is generated by the LLM if api_client is provided, otherwise
    a heuristic summary is used (faster, less accurate).

    Strategy:
      1. Keep all system messages
      2. Take the last N conversation messages verbatim
      3. Summarize everything in between
      4. Insert summary as a synthetic assistant message
    """
    convo = session.conversation_messages()
    sys_msgs = session.system_messages()

    if len(convo) <= preserve_recent + 2:
        return session  # Nothing to compact

    # Split: messages to summarize, messages to preserve
    to_summarize = convo[:-preserve_recent]
    to_preserve = convo[-preserve_recent:]

    summary_text = _generate_summary(to_summarize, api_client)

    # Build new session
    new_session = Session(version=session.version, metadata=dict(session.metadata))
    for sm in sys_msgs:
        new_session.append(sm)

    # Insert summary as a synthetic user message (so the model treats it as context)
    summary_msg = Message(
        role=MessageRole.USER,
        blocks=[ContentBlock.text_block(
            f"[CONTEXT SUMMARY of earlier investigation]\n{summary_text}\n"
            f"[END SUMMARY — continue investigation from here]"
        )],
    )
    new_session.append(summary_msg)

    for pm in to_preserve:
        new_session.append(pm)

    logger.info(
        "Compacted session: %d messages -> %d messages (saved ~%d tokens)",
        len(convo),
        len(new_session.conversation_messages()),
        estimate_session_tokens(session) - estimate_session_tokens(new_session),
    )

    return new_session


def _generate_summary(messages: List[Message], api_client=None) -> str:
    """Generate a digest of old messages.

    If api_client is provided, use the LLM. Otherwise use a fast heuristic.
    """
    if api_client is not None:
        return _llm_summary(messages, api_client)
    return _heuristic_summary(messages)


def _heuristic_summary(messages: List[Message]) -> str:
    """Fast non-LLM summary: list tool calls + extract key text mentions."""
    tool_calls = []
    findings = []

    for msg in messages:
        if msg.role == MessageRole.ASSISTANT:
            for block in msg.blocks:
                if block.block_type == "tool_use":
                    params = block.tool_input or {}
                    key_param = next(iter(params.values()), "")
                    tool_calls.append(f"{block.tool_name}({key_param})")
                elif block.block_type == "text" and block.text:
                    # Pull out key phrases
                    for line in block.text.split("\n"):
                        line = line.strip()
                        if any(kw in line.lower() for kw in (
                            "vulnerab", "finding", "exploit", "malicious",
                            "ioc:", "c2:", "injection", "overflow",
                            "cwe-", "confirmed", "suspect",
                        )):
                            findings.append(line[:200])

    parts = []
    if tool_calls:
        parts.append(f"Earlier tool calls: {', '.join(tool_calls[:30])}")
    if findings:
        parts.append("Key observations from earlier analysis:")
        for f in findings[:15]:
            parts.append(f"  - {f}")
    if not parts:
        parts.append(f"Earlier investigation: {len(messages)} messages exchanged.")

    return "\n".join(parts)


def _llm_summary(messages: List[Message], api_client) -> str:
    """LLM-generated summary of old messages."""
    transcript = "\n\n".join(
        f"[{m.role.value}] " + " ".join(
            (b.text or b.tool_output or f"{b.tool_name}({b.tool_input})" or "")
            for b in m.blocks
        )[:500]
        for m in messages
    )
    summary_prompt = (
        "Summarize the following binary analysis investigation transcript. "
        "Preserve: tools called, addresses examined, findings discovered, "
        "and key reasoning. Be concise (under 500 words).\n\n"
        f"---\n{transcript}\n---\n\nSummary:"
    )

    try:
        response, _ = api_client.call(
            messages=[Message.user(summary_prompt)],
            system_prompt="You are a concise technical summarizer.",
            max_tokens=600,
        )
        return response.strip()
    except Exception as e:
        logger.warning("LLM summary failed: %s; falling back to heuristic", e)
        return _heuristic_summary(messages)
